
import { ColorOption } from './types';

export const COLORS: ColorOption[] = [
  // LEROY MERLIN - BLANCS I NATURALS
  { name: 'White 0', hex: '#FFFFFF', brand: 'Leroy Merlin' },
  { name: 'Blanco 1', hex: '#F9F9F9', brand: 'Leroy Merlin' },
  { name: 'Paper 2', hex: '#E8E3DD', brand: 'Leroy Merlin' },
  { name: 'Paper 5', hex: '#D0C9C0', brand: 'Leroy Merlin' },
  { name: 'Cream 2', hex: '#F9F1E7', brand: 'Leroy Merlin' },
  { name: 'Cream 5', hex: '#F5E6D3', brand: 'Leroy Merlin' },
  { name: 'Kenya 4', hex: '#C5A184', brand: 'Leroy Merlin' },
  { name: 'Moon 4', hex: '#D1D5DB', brand: 'Leroy Merlin' },

  // LEROY MERLIN - TERRES
  { name: 'Moka 2', hex: '#8E7662', brand: 'Leroy Merlin' },
  { name: 'Trench 5', hex: '#B2A496', brand: 'Leroy Merlin' },
  { name: 'Trench 6', hex: '#9A8C7F', brand: 'Leroy Merlin' },
  { name: 'Terra 5', hex: '#957365', brand: 'Leroy Merlin' },
  { name: 'Terra 6', hex: '#7D5B4F', brand: 'Leroy Merlin' },
  { name: 'Pecan 4', hex: '#BCAB9D', brand: 'Leroy Merlin' },
  { name: 'Pecan 5', hex: '#A28D7F', brand: 'Leroy Merlin' },
  { name: 'Pecan 6', hex: '#867468', brand: 'Leroy Merlin' },
  { name: 'Havana 3', hex: '#A1887F', brand: 'Leroy Merlin' },
  { name: 'Havana 6', hex: '#6F4E37', brand: 'Leroy Merlin' },
  { name: 'Fossil 2', hex: '#B7B2AD', brand: 'Leroy Merlin' },
  { name: 'Fossil 6', hex: '#706B65', brand: 'Leroy Merlin' },
  { name: 'Eva 3', hex: '#FFCCBC', brand: 'Leroy Merlin' },
  { name: 'Eva 5', hex: '#D9C5B2', brand: 'Leroy Merlin' },

  // LEROY MERLIN - GRISOS
  { name: 'Black 0', hex: '#1A1A1B', brand: 'Leroy Merlin' },
  { name: 'Granit 1', hex: '#F3F4F6', brand: 'Leroy Merlin' },
  { name: 'Granit 2', hex: '#E5E7EB', brand: 'Leroy Merlin' },
  { name: 'Granit 3', hex: '#D1D5DB', brand: 'Leroy Merlin' },
  { name: 'Granit 5', hex: '#6B7280', brand: 'Leroy Merlin' },
  { name: 'Granit 6', hex: '#4B5563', brand: 'Leroy Merlin' },
  { name: 'Khol 4', hex: '#6B7280', brand: 'Leroy Merlin' },
  { name: 'Khol 6', hex: '#374151', brand: 'Leroy Merlin' },
  { name: 'Smoke 6', hex: '#4A4A4A', brand: 'Leroy Merlin' },
  { name: 'Cool 2', hex: '#CBD5E1', brand: 'Leroy Merlin' },

  // LEROY MERLIN - BLAUS
  { name: 'Balsamo 0', hex: '#E0F2F1', brand: 'Leroy Merlin' },
  { name: 'Miami 1', hex: '#B2EBF2', brand: 'Leroy Merlin' },
  { name: 'Miami 2', hex: '#80DEEA', brand: 'Leroy Merlin' },
  { name: 'Miami 4', hex: '#00BCD4', brand: 'Leroy Merlin' },
  { name: 'Miami 6', hex: '#00838F', brand: 'Leroy Merlin' },
  { name: 'Fjord 1', hex: '#E0F7FA', brand: 'Leroy Merlin' },
  { name: 'Fjord 3', hex: '#4DD0E1', brand: 'Leroy Merlin' },
  { name: 'Fjord 4', hex: '#26C6DA', brand: 'Leroy Merlin' },
  { name: 'Fjord 6', hex: '#00838F', brand: 'Leroy Merlin' },
  { name: 'Ink 5', hex: '#006064', brand: 'Leroy Merlin' },
  { name: 'Saphir 2', hex: '#0277BD', brand: 'Leroy Merlin' },
  { name: 'Sloop 2', hex: '#1E88E5', brand: 'Leroy Merlin' },
  { name: 'Aqua 6', hex: '#006064', brand: 'Leroy Merlin' },

  // LEROY MERLIN - VERDS
  { name: 'Esmeralda 0', hex: '#00897B', brand: 'Leroy Merlin' },
  { name: 'Forest 3', hex: '#43A047', brand: 'Leroy Merlin' },
  { name: 'Forest 4', hex: '#2E7D32', brand: 'Leroy Merlin' },
  { name: 'Forest 6', hex: '#1B5E20', brand: 'Leroy Merlin' },
  { name: 'Sage 3', hex: '#90A4AE', brand: 'Leroy Merlin' },
  { name: 'Sage 4', hex: '#81C784', brand: 'Leroy Merlin' },
  { name: 'Sage 5', hex: '#455A64', brand: 'Leroy Merlin' },
  { name: 'Cactus 5', hex: '#4CAF50', brand: 'Leroy Merlin' },
  { name: 'Cactus 6', hex: '#388E3C', brand: 'Leroy Merlin' },
  { name: 'Mint 3', hex: '#4DB6AC', brand: 'Leroy Merlin' },
  { name: 'Mint 6', hex: '#004D40', brand: 'Leroy Merlin' },
  { name: 'Laguna 2', hex: '#80CBC4', brand: 'Leroy Merlin' },
  { name: 'Sierra 2', hex: '#A5D6A7', brand: 'Leroy Merlin' },
  { name: 'Bali 2', hex: '#80CBC4', brand: 'Leroy Merlin' },
  { name: 'Wake 3', hex: '#81D4FA', brand: 'Leroy Merlin' },
  { name: 'Celadon 4', hex: '#AFE1AF', brand: 'Leroy Merlin' },

  // LEROY MERLIN - GROCS I TARONGES
  { name: 'Banana 1', hex: '#FFF59D', brand: 'Leroy Merlin' },
  { name: 'Banana 3', hex: '#FFF176', brand: 'Leroy Merlin' },
  { name: 'Banana 5', hex: '#FBC02D', brand: 'Leroy Merlin' },
  { name: 'Banana 6', hex: '#F9A825', brand: 'Leroy Merlin' },
  { name: 'Solemio 1', hex: '#FDD835', brand: 'Leroy Merlin' },
  { name: 'Cotta 4', hex: '#BF360C', brand: 'Leroy Merlin' },
  { name: 'Sevent 5', hex: '#E64A19', brand: 'Leroy Merlin' },

  // LEROY MERLIN - ROJOS I VIVIUS
  { name: 'Chili 6', hex: '#B71C1C', brand: 'Leroy Merlin' },
  { name: 'Carmen 2', hex: '#C62828', brand: 'Leroy Merlin' },
  { name: 'Cocktail 1', hex: '#FF8A65', brand: 'Leroy Merlin' },
  { name: 'Litchi 2', hex: '#F06292', brand: 'Leroy Merlin' },
  { name: 'Lava 3', hex: '#D32F2F', brand: 'Leroy Merlin' },
  { name: 'Bistro 2', hex: '#795548', brand: 'Leroy Merlin' },
  { name: 'Bistro 6', hex: '#3E2723', brand: 'Leroy Merlin' },
  { name: 'Crimson 2', hex: '#D32F2F', brand: 'Leroy Merlin' },
  { name: 'Candy 3', hex: '#F48FB1', brand: 'Leroy Merlin' },
  { name: 'Flush 5', hex: '#FF5722', brand: 'Leroy Merlin' },
  { name: 'Kiss 5', hex: '#AD1457', brand: 'Leroy Merlin' },
  { name: 'Kiss 6', hex: '#880E4F', brand: 'Leroy Merlin' },
  { name: 'Orchid 2', hex: '#CE93D8', brand: 'Leroy Merlin' },
  { name: 'Santal 4', hex: '#5D4037', brand: 'Leroy Merlin' },
  { name: 'Bohemia 6', hex: '#4A148C', brand: 'Leroy Merlin' },
  { name: 'Elixir 6', hex: '#311B92', brand: 'Leroy Merlin' },
  { name: 'Berry 3', hex: '#9C27B0', brand: 'Leroy Merlin' },
  { name: 'Berry 6', hex: '#4A148C', brand: 'Leroy Merlin' },

  // BAUHAUS - PALETTE UPDATE
  { name: 'Gropius Red BH-101', hex: '#B22222', brand: 'Bauhaus' },
  { name: 'Bauhaus Gelb BH-102', hex: '#FFD700', brand: 'Bauhaus' },
  { name: 'Primary Blue BH-103', hex: '#00539C', brand: 'Bauhaus' },
  { name: 'Warm Terracotta BH-104', hex: '#C06C4E', brand: 'Bauhaus' },
  { name: 'Weimar White BH-201', hex: '#F5F5F1', brand: 'Bauhaus' },
  { name: 'Industrial Grey BH-202', hex: '#708090', brand: 'Bauhaus' },
  { name: 'Concrete Ash BH-203', hex: '#A9A9A9', brand: 'Bauhaus' },
  { name: 'Steel Beam BH-204', hex: '#4682B4', brand: 'Bauhaus' },
  { name: 'Anthracite Black BH-205', hex: '#2F4F4F', brand: 'Bauhaus' },
  { name: 'Sage Bauhaus BH-301', hex: '#8FBC8F', brand: 'Bauhaus' },
  { name: 'Canvas Beige BH-302', hex: '#E5D3B3', brand: 'Bauhaus' },
  { name: 'Muted Petrol BH-303', hex: '#3E5F61', brand: 'Bauhaus' },
  { name: 'Dessau Greige BH-304', hex: '#BDB76B', brand: 'Bauhaus' },
  { name: 'Linear Graphite BH-401', hex: '#363636', brand: 'Bauhaus' },
  { name: 'Oatmeal Texture BH-402', hex: '#DCD5C1', brand: 'Bauhaus' },

  // HIPER DECORACIÓN - CATÁLOGO INTERIOR
  { name: 'Blanco Nieve HD-001', hex: '#FFFFFF', brand: 'Hiper Decoración' },
  { name: 'Blanco Roto HD-002', hex: '#F8F9F5', brand: 'Hiper Decoración' },
  { name: 'Gris Perla HD-110', hex: '#D9D9D9', brand: 'Hiper Decoración' },
  { name: 'Gris Niebla HD-112', hex: '#B3B3B3', brand: 'Hiper Decoración' },
  { name: 'Hueso Profundo HD-205', hex: '#F5F5DC', brand: 'Hiper Decoración' },
  { name: 'Arena Suave HD-T20', hex: '#E2D1B3', brand: 'Hiper Decoración' },
  { name: 'Piedra Natural HD-T22', hex: '#918E85', brand: 'Hiper Decoración' },
  { name: 'Verde Oliva HD-T45', hex: '#556B2F', brand: 'Hiper Decoración' },
  { name: 'Azul Báltico HD-T60', hex: '#2C3E50', brand: 'Hiper Decoración' },
  { name: 'Ocre Tostado HD-T15', hex: '#B87333', brand: 'Hiper Decoración' },
  { name: 'Malva Ceniza HD-T88', hex: '#918181', brand: 'Hiper Decoración' },
  { name: 'Terracota Suave HD-T34', hex: '#C2452D', brand: 'Hiper Decoración' },
  { name: 'Antracita Sellante CT1-ANTA', hex: '#2C2C2C', brand: 'Hiper Decoración' },
  { name: 'Azul Pizarra TK-PIZN', hex: '#34495E', brand: 'Hiper Decoración' },
  { name: 'Nepal Gris Suave BR-508', hex: '#A9A9A9', brand: 'Hiper Decoración' },
  { name: 'Egipto Ocre BR-520', hex: '#CC7722', brand: 'Hiper Decoración' },
  { name: 'Japón Blanco BR-530', hex: '#F8F8FF', brand: 'Hiper Decoración' },
];

export const PRIMARY_COLOR = '#3db7b3';
